### ISSUE TITLE
Not really an issue ^^

### ISSUE THREAD

**Issue by JackCeparou** [RuneBarrett/ThudPlugins#3]
Hi RuneB,

I'm sure users would love to have your plugins in the [new home](http://www.ownedcore.com/forums/diablo-3/turbohud/) ; )

Regards,
Jack.

**Comment by RuneBarrett** [comment]
Awesome! Thanks. Back in action!
![giphy](https://cloud.githubusercontent.com/assets/7199742/24481341/e821d700-14e9-11e7-946d-df775784164b.gif)
